### PR TITLE
471 add service files

### LINKED ISSUE #471: Add systemd .services files into the git repository?
Dear all,

thank you very much for creating kanidm :-)

I am trying to create a working package for Arch Linux ... I was wondering if it would be possible to include the systemd .service files to this repository, maybe in the examples folder together with the other config examples.

Currently, the files were taken from 
https://build.opensuse.org/package/show/home:firstyear:kanidm/kanidm
and are somewhat disconnected, I would say.

I think you would also need these service files if you build and install from source, so it might be nice to ship it with the repo?

If that makes sense and you agree, I could also include them and create a PR for that.

Thank you very much in advance for your advice.

### PR DESCRIPTION
**Pull request by cuberoot74088**
Fixes #471 

Here is a proposal to include the current `.service` files from https://build.opensuse.org/package/show/home:firstyear:kanidm/kanidm into this repo. 

As the files come from openSUSE, I have put the files into `platform/opensuse/<*.service>` as proposed.

Looking forward to comments and suggestions.

- [-] cargo fmt has been run
- [-] cargo clippy has been run
- [-] cargo test has been run and passes
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

### CODE REVIEW

**Comment by Firstyear** [comment]
@yaleman this looks good to me, you cool with this? I'll need to adjust the suse rpm for it later.

**Review by Firstyear — APPROVED** [review]

**Comment by cuberoot74088** [comment]
> @yaleman this looks good to me, you cool with this? I'll need to adjust the suse rpm for it later.

What kind of adjustment are you thinking of? Would you remove the files from there and use them from the repo? 

In that case, I should probably remove the first line wtih "Source" comment. Don't know if you have seen that.

**Review by yaleman — APPROVED** [review]
The ReadWritePaths on `kanidm-unixd-tasks` might cause issues if you've got a non-standard homedir path, but these definitely are a good base :)

**Comment by cuberoot74088** [comment]
Is there still something to do or improve from my/your side?

**Comment by Firstyear** [comment]
Nope, this is all good :)

**Pull request merged**
