### PR TITLE
Change how domain names are handled in our configuration.

### LINKED ISSUE #623: Don't set default domain_name `example.com`
Continuing https://github.com/kanidm/kanidm/pull/617#issuecomment-978373115 here.

As I already laid out, I think it's an unintuitive situation that `domain_name` is currently set to `example.com` at first startup and then must be changed by the user. A server that is configured with `example.com` is unusable for every situation (except in integration tests), but pretends to be in a state where everything is configured properly.

From a user side the ideal solution imo would be:

When no `domain_name` is set yet, the server quickly fails, communicating what needs to be done to the user.

```
$ kanidmd server
Creating db...
There is currently no domain_name set. Run `kanidmd domain_name_change` to set one. Also see the docs here blabla
```

~~Also it would be nice to have `kanidmd domain_name_change` create the db at startup if it doesn't exist yet, so it would be optional to run `kanidmd server` first.~~

### PR DESCRIPTION
**Pull request by Firstyear**
Fixes #623 - Improve domain name handling on server startup. Rather than starting with a default domain and expecting a rename, we make the domain name a config value in server.toml. When the server starts up, we use this initially to create the first domain name. When a domain rename is requested, we read the value from server.toml (and skip the origin check by not starting the idms layer).  Finally, this adds a config tester that can check if the server "would start" with this configuration. As always, book chapters have been updated too :) 

- [ x ] cargo fmt has been run
- [ ] cargo clippy has been run
- [ x ] cargo test has been run and passes
- [ x ] book chapter included (if relevant)
- [ ] design document included (if relevant)

### CODE REVIEW

**Comment by Firstyear** [comment]
I think the only think missing right now, is a check that domain in db == server config domain at startup. I'm going to think where to put this :)

**Comment by yaleman** [comment]
All looks sensible here, especially once the "compare db to domain name" bit is in 😄 

it'll happily start/pass configtest regardless of what's in the various options, and if I use kanidm.example.com.au while origin is kanidm.example.com - which ... would technically ***start***, but not ***work***

**Comment by Firstyear** [comment]
@yaleman I changed it a bit, it won't fail to start the server if the config mismatches, but it will always prefer a db domain name over the config one, and will warn in the case you have it mis-configured. 

```
+00:00 WARN     🚧 [admin.warn]: Using database configured domain name idm.example.com - was example.com
+00:00 WARN     🚧 [admin.warn]: If you think this is an error, see https://kanidm.github.io/kanidm/administrivia.html#rename-the-domain
```

Otherwise I'm pretty happy with it now.

**Comment by Firstyear** [comment]
Okay, deployed and running this on my instance now, seem happy. Any objections to merging?

**Review by yaleman — APPROVED** [review]
I see no issue with the changes as proposed, with the testing I've done.

**Pull request merged**
