### PR TITLE
1355 docker builds

### LINKED ISSUE #1355: Improve docker builds
Currently it can be a bit awkward/slow to do docker builds, or you need a weird setup with buildx for multiple arch releases. 

To improve this we should consider:

* Vendor deps first
* Having a "setup" phase that setups a single builder that can be used to help with build caching.
* Setting up cross-complilation ( https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/ )

### PR DESCRIPTION
**Pull request by Firstyear**
Fixes #1355 - This improves docker builds with a cache for metadata and packages, and removes steps that aren't needed. There is a bug in zypper which when resolved will improve things again. 

Oh and this cleans up profiles with cpu arches and arch features  :) 

- [ x ] cargo fmt has been run
- [ ] cargo clippy has been run
- [ x ] cargo test has been run and passes
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

### CODE REVIEW

**Comment by Firstyear** [comment]
Actually, I think we can use the same cache strategy on the rust target folder ....

**Comment by Firstyear** [comment]
Ready to review :)

**Comment by yaleman** [comment]
Just noticed the radius build popped, will check in the morning

**Comment by Firstyear** [comment]
I had a look but I can't figure our the radius thing, it looks like github has a really old version of the image? Maybe we need --pull somewhere?

**Review by yaleman — APPROVED** [review]

**Comment by yaleman** [comment]
Looks like the remaining issues have something to do with upstream mirrors as discussed... not much we can do at this point 😢

**Comment by Firstyear** [comment]
We did our best <3

**Pull request merged**
