### PR TITLE
Absolutely minimal implementation

### LINKED ISSUE #1710: 401 response on failed login attempt
**Is your feature request related to a problem? Please describe.**

I currently have kanidm proxied by nginx and the access log returns a 404 on wrong usernames (which is good), but a 200 response on failed password attempts. I would think that a 401 would make sense here, and maybe in the wrong username case as well. Here's some example nginx logs, where the 404 was from an incorrect username, and the final 200 response was from an invalid password:
```
10.0.0.231 - - [07/Jun/2023:01:18:58 +0000] "POST /v1/auth HTTP/2.0" 404 19 "https://idm.example.com/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0"
10.0.0.231 - - [07/Jun/2023:01:19:06 +0000] "POST /v1/auth HTTP/2.0" 200 84 "https://idm.example.com/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0"
10.0.0.231 - - [07/Jun/2023:01:19:06 +0000] "POST /v1/auth HTTP/2.0" 200 86 "https://idm.example.com/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0"
10.0.0.231 - - [07/Jun/2023:01:19:10 +0000] "POST /v1/auth HTTP/2.0" 200 92 "https://idm.example.com/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0"
```
Here's the kanidm logs to match the failed username:
```
6f87c797-d578-43f6-b382-da6a77c8bd03 INFO     ┝━ auth [ 273µs | 65.14% ]
6f87c797-d578-43f6-b382-da6a77c8bd03 INFO     │  ┝━ ｉ [info]: Begin auth event | event_tag_id: 9 | sessionid: None | req: AuthRequest { step: Init2 { username: "a", issue: Cookie } }
6f87c797-d578-43f6-b382-da6a77c8bd03 INFO     │  ┕━ ｉ [info]: Sending auth result | event_tag_id: 9 | res: Err(NoMatchingEntries)
6f87c797-d578-43f6-b382-da6a77c8bd03 WARN     ┕━ 🚧 [warn]: Client error --> Response sent | event_tag_id: 5 | status: 404 - Not Found
```
Failed password:
```
dd8e8822-ea5d-4880-b89f-3deef68cb9e8 INFO     ┝━ auth [ 17.7ms | 99.34% ]
dd8e8822-ea5d-4880-b89f-3deef68cb9e8 INFO     │  ┝━ ｉ [info]: Begin auth event | event_tag_id: 9 | sessionid: Some(00000000-647f-db0a-0b27-de21991ea811) | req: AuthRequest { step: Cred(Password(_)) }
dd8e8822-ea5d-4880-b89f-3deef68cb9e8 ERROR    │  ┝━ 🚨 [error]: Handler::Password -> Result::Denied - incorrect password | event_tag_id: 11
dd8e8822-ea5d-4880-b89f-3deef68cb9e8 INFO     │  ┝━ ｉ [info]: Credentials denied | event_tag_id: 9 | reason: incorrect password
dd8e8822-ea5d-4880-b89f-3deef68cb9e8 INFO     │  ┕━ ｉ [info]: Sending auth result | event_tag_id: 9 | res: Ok(AuthResult { sessionid: 00000000-647f-db0a-0b27-de21991ea811, state: AuthState::Denied("incorrect password") })
dd8e8822-ea5d-4880-b89f-3deef68cb9e8 INFO     ┕━ ｉ [info]: --> Response sent | event_tag_id: 6 | status: 200 - OK
```

**Describe the solution you'd like**

Return a 401 (or something more appropriate) on failed authentication. There maybe something I'm overlooking, but this would make it super easy to parse for bad attempts, and then I can configure fail2ban to match.

**Describe alternatives you've considered**

An access log would be also great, similar to what is described in https://github.com/kanidm/kanidm/issues/22. I could parse that with fail2ban, and then ban malicious IP addresses.

**Additional context**

I have a oauth2-proxy communicating with kanidm oauth2/oidc to validate login requests using the `auth_request` directive in nginx. I want to expose some webservers publicly, but want to be able to block malicious IP addresses with fail2ban, since I was planning to have kanidm be the first intercepted service

### PR DESCRIPTION
**Pull request by Firstyear**
Fixes #1710 

Refers #22 

This is the absolute minimal impl of event audit for logins. Currently we just report on authentication denied.

I think we need to expand the data we return here, the important one is likely the source ip of the event, but that's going to be a bit more work to wire in - part of me thinks it would be worth just swapping to axum now to save the double handling later .... 

- [ x ] This pr contains no AI generated code
- [ x ] cargo fmt has been run
- [ x ] cargo clippy has been run
- [ x ] cargo test has been run and passes
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

### CODE REVIEW

**Comment by Firstyear** [comment]
@dlrobson Can you comment what data you would like in the audit event? I'm guessing at the least IP address and account uuid / name

**Comment by dlrobson** [comment]
Thanks @Firstyear for getting this together so quick! I think what you suggested would be ideal, along with the timestamp that the attempt occurred at. I can't think of anything else that would be useful.

Would you also log Username/TOTP/Password attempts as well?

**Comment by Firstyear** [comment]
This reports on auth denied for all possible denial cases - webauthn invalid, password, totp, etc. 

I'll see about getting the other details in today :) IPAddress will be the fun one but I think it's doable.

**Comment by Firstyear** [comment]
Adds support for ips and other details. We also emit the data as json. This is pretty minimal still but it gives what you want @dlrobson 

```
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]:  | audit_event: {"AuthenticationDenied":{"source":{"Https":"127.0.0.1"},"uuid":"00000000-0000-0000-0000-000000000000","spn":"admin@localhost","time":1686198334}}
```

As an example of what this does. Time is unix timestamp.

**Comment by dlrobson** [comment]
Thanks @Firstyear! I should be able to work with this :) Thanks for the quick turnaround!

**Comment by Firstyear** [comment]
> Wewt, nice work!
> 
> Edited your PR comment so we don't auto-close #22 because that's an epic in itself...

Fair enough. Most of the framework is there now, we just need to actually wire in more events and the possible outputs for those :)

**Comment by Firstyear** [comment]
@dlrobson I'll update the devel container images in the next 8 hours for you to start using it :)

**Comment by dlrobson** [comment]
Thanks @Firstyear! Sorry to keep bugging you. I just pulled the latest build, and I think there might be a small bug. This is what I'm seeing:
```
7ae454b3-4d25-4236-93bd-67ba26b60426 INFO     tide-request [ 103µs | 100.00% ]
7ae454b3-4d25-4236-93bd-67ba26b60426 INFO     ┝━ ｉ [info]: Request received | event_tag_id: 9 | remote_addr: "72.24.19.178" | http.host: "idm.example.com" | http.method: "POST" | path: "/v1/auth"
7ae454b3-4d25-4236-93bd-67ba26b60426 ERROR    ┝━ 🚨 [error]: Unable to process remote addr, refusing to proceed
7ae454b3-4d25-4236-93bd-67ba26b60426 ERROR    ┕━ 🚨 [error]: Internal error -> Response sent | event_tag_id: 4 | message: unable to validate peer address | error_type: "?" | status: 500 - Internal Server Error
```

Which I think is [here](https://github.com/kanidm/kanidm/pull/1711/files#diff-fb54b766a3ec8982eedf95e36742687d4532625889784056c547dafdd03bd256R1102) in the PR. I don't think it's my nginx conf since the log above shows the expected IP address. I think it's just not always getting passed around properly?

Also, would you like me to make a proper issue ticket for this, or is it okay to have this conversation here?

**Pull request merged**
