### PR TITLE
expose group patch for parity

### PR DESCRIPTION
**Pull request by dvv**
Harmonizes API.

Checklist

- [X] This pr contains no AI generated code
- [ ] cargo fmt has been run
- [ ] cargo clippy has been run
- [ ] cargo test has been run and passes
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

### CODE REVIEW

**Review by Firstyear — APPROVED** [review]
Also make sure you are in contributors.md if you wish.

**Review by yaleman — CHANGES_REQUESTED** [review]
Can you please add a test covering this change? It's relatively simple to a kanidmd_testkit-based test, see examples here: https://github.com/yaleman/kanidm/blob/4cac078ca908513f3e6592b7f82cf0b451831935/server/testkit/tests/proto_v1_test.rs#L83

**Comment by dvv** [comment]
I won't be able to run the tests on my constrained setup.

**Comment by Firstyear** [comment]
How .... constrained is your machine. Like really?

**Comment by dvv** [comment]
Like a remote session to a docker-able several core 4Gb-ram something.
It's a pain even to `make build/kanidmd` there (the errors are swallowed by server/Dockerfile) and I have to _guess_ what went wrong )

**Comment by yaleman** [comment]
If you push them up to github the tests will run automagically

**Comment by dvv** [comment]
Well, I can't see any `person_id_patch` tests to copy. Sorry if this PR is not welcome.

**Comment by Firstyear** [comment]
> Well, I can't see any `person_id_patch` tests to copy. Sorry if this PR is not welcome.

No it's not that it's not welcome at all. We are just trying to do better with testing of API's because historically we weren't as good at it. So we try to always ask new features to "do better than before" is why we asked for you to add the test. 

Leave this PR here, and we can add the tests. I don't see anything wrong code wise.

**Comment by dvv** [comment]
I do understand the value of tests. I would go github-will-test way if I i) knew Rust and its testing pattern, or ii) encountered reference tests on `person_id_patch` )
Tnx

**Comment by yaleman** [comment]
Fixed the existing person patch test and added a group one. TBH exposing the `perform_<method>_request` methods makes sense from client, for these kinds of things...

**Review by yaleman — APPROVED** [review]

**Review by Firstyear — APPROVED** [review]

**Comment by Firstyear** [comment]
Coming back to this, @dvv I don't see how you couldn't have checked this.

```
time -l cargo check
       55.99 real       298.05 user        43.65 sys
          1584627712  maximum resident set size // 1.5GB ram max
```

```
# Note this only builds the required proto tests we are interested in, rather than all tests
time -l cargo test --test proto_v1_test  test_v1_group_id_patch
       77.11 real       417.88 user        31.51 sys
          3495444480  maximum resident set size // 3.4GB max
```

```
# As above with some hyper optimised compiler flags
time -l cargo test --test proto_v1_test  test_v1_group_id_patch
      104.95 real       722.05 user        38.86 sys
          3208167424  maximum resident set size // 3.2GB max
```

```
# Test already compiled to show max test ram usage.
time -l cargo test test_v1_group_id_patch
        0.37 real         0.21 user         0.14 sys
            81330176  maximum resident set size // 0.08GB max
```

Potentially you can also lower this further.

**Comment by dvv** [comment]
This is because grepping "*.rs" for "person_id_patch" gave no results.
Thanks for applying!

**Comment by yaleman** [comment]
We're only human, not everything's named perfectly - I'd probably suggest searching by the url, etc in future, that's how I found it 😄

**Pull request merged**
