### PR TITLE
PyKanidm updates and testing

### PR DESCRIPTION
**Pull request by yaleman**
Checklist

- [x] This pr contains no AI generated code
- [x] cargo fmt has been run
- [x] cargo clippy has been run
- [x] cargo test has been run and passes
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

### CODE REVIEW

**Comment by yaleman** [comment]
@sbordeyne I'm working on things here

**Comment by sbordeyne** [comment]
For the checklist of things to implement:

- [x] group create
- [ ] group update
- [x] group delete
- [x] person create
- [x] person get
- [ ] person update
- [x] person list
- [ ] person delete
- [ ] add members to group
- [ ] remove members from group
- [ ] upload pw-badlist
- [ ] remove password from badlist
- [ ] get password badlist (need to diff to upload just the new ones, remove the old ones)
- [x] list/get oauth2 client
- [x] create oauth2 client
- [x] delete oauth2 client
- [ ] update oauth2 client
- [ ] update/delete oauth2 scope mapping
- [ ] set landing URL for oauth2 client
- [ ] set domain display name
- [ ] set LDAP base DN
- [ ] add/delete person SSH public key
- [x] create/update/delete person
- [x] create/update/delete service account
- [x] generate service account api token
- [ ] destroy service account API token
- [ ] add/remove SSH public keys to service accounts


Furthermore, I need a way to get the admin credentials from the started up pod. I think I can manage with the implementation as it is now by using the kubernetes API to exec a command in the created pod, but it's a bit clunky. Though exposing that info to the outside might be a bit too unsecure so I don't mind working around that.

Feel free to check boxes as you work on them, I'm trying to be as exhaustive as possible so that it's one and done. If you can upload the package to pypi regularly (even in a WIP state) with a version matching the kanidm server version it would be great ! (i.e. 1.1.0.beta14.alpha1 -> once the client is stable it would probably be 1.1.0.beta14). I'm using poetry for my dependency management and it doesn't quite like installing from git with a subpath it seems.

**Comment by yaleman** [comment]
> I need a way to get the admin credentials from the started up pod

That's a bootstrap problem, I don't see us changing the `recover-account` flow.

**Comment by yaleman** [comment]
> I'm using poetry for my dependency management and it doesn't quite like installing from git with a subpath it seems.

You can use [poetry's subdir support](https://python-poetry.org/blog/announcing-poetry-1.2.0/#subdirectory-support-for-git-dependencies) to install it directly:

```toml
[tool.poetry.dependencies.kanidm]
git = "git@github.com:yaleman/kanidm.git"
branch = "yaleman/issue282"
subdirectory = "pykanidm"
```

I'm not going to be messing around with incremental `pip` releases of *more* janky beta things 😄

**Comment by yaleman** [comment]
How's it look @sbordeyne? I think I'm done for now.

**Review by sbordeyne — APPROVED** [review]
I had a look, and it seems to be everything needed. I think the overall coverage would go down, but maybe that can be done later

**Comment by sbordeyne** [comment]
I'll have a test around to see what the API responses are to type my operator properly, since the models are not defined

**Comment by yaleman** [comment]
> I'll have a test around to see what the API responses are to type my operator properly, since the models are not defined

It'd be good for you/someone to take on typing the responses properly, I realistically just don't have time for it at the moment.

**Comment by sbordeyne** [comment]
I had a try, I ran kanidm in plain docker to test out the client (followed the evaluation quickstart guide, `kanidm/server:latest` image), and I had some issues:

## Authentication

The authentication is a bit weird to handle, though I managed

```python
client = KanidmClient(config=config)
auth = await client.authenticate_password()
client.config.auth_token = auth.state.success
```
allowed me to make authenticated calls using the `admin` user (`idm_admin` should therefore work as well)

The current process forces the operator to authenticate at each operation, which is not ideal, but for a first version it's good enough.

## Create user

`await client.person_account_create("test", "test")` breaks, because `display_name` is not an allowed attribute

```
ClientResponse(content='{"invalidattributename":"display_name"}', data={'invalidattributename': 'display_name'}, headers={'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '39', 'Cache-Control': 'no-store no-cache max-age=0', 'Pragma': 'no-cache', 'content-security-policy': "base-uri 'self' https:; default-src 'self'; form-action 'self' https:; frame-ancestors 'none'; img-src 'self' data:; script-src 'self' 'unsafe-eval' 'sha384-/QjFORk6bA5FyNPkoloalvH76n28OempQ2ob9Q7k3F+Zxvj0vRNFVL+3+jxrepJu' 'sha384-0uatzEXfdYqVGmohDtRUZMSrZ1aBHbv7SYLEIkusNmUNJPo7K6DC8evTIOFdlU4w' 'sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM' 'sha384-Rw3AP/PSCWhQsOA9lwKQ02luSPa9fZgWLtCOKxopHsFosFOrQB5B00t2FoQ4HfJL' 'sha384-kZ2o2DO3rYuS/QkJv66LS3soqapWfnBpcQqnujbLHP8B0JIye0NiaI0SIuwOGJPW'; worker-src 'none';", 'x-content-type-options': 'nosniff', 'permissions-policy': 'fullscreen=(), geolocation=()', 'referrer-policy': 'no-referrer-when-downgrade', 'x-kanidm-version': '1.1.0-rc.15', 'strict-transport-security': 'max-age=86400', 'x-kanidm-opid': '67ff3584-e93d-4371-aff0-db4c8a9d2547', 'Date': 'Wed, 15 Nov 2023 23:02:41 GMT'}, status_code=500)
```

## Group create

API error ? The group create endpoint doesn't return anything ?
```
>>> await client.group_create("test")
ERROR:root:Failed to JSON Decode Response: Expecting value: line 1 column 1 (char 0)
ERROR:root:Response data: b''
ClientResponse(content='', data=None, headers={}, status_code=-1)
```

## Service account create

same error as with the person create

## password append

badlist_passwordpayload is not correct ?

```
>>> await client.system_password_badlist_append(["zzzzzzzzzzzz"])
ClientResponse(content='{"invalidattributename":"badlist_passwordpayload"}', data={'invalidattributename': 'badlist_passwordpayload'}, headers={'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '50', 'Cache-Control': 'no-store no-cache max-age=0', 'Pragma': 'no-cache', 'content-security-policy': "base-uri 'self' https:; default-src 'self'; form-action 'self' https:; frame-ancestors 'none'; img-src 'self' data:; script-src 'self' 'unsafe-eval' 'sha384-/QjFORk6bA5FyNPkoloalvH76n28OempQ2ob9Q7k3F+Zxvj0vRNFVL+3+jxrepJu' 'sha384-0uatzEXfdYqVGmohDtRUZMSrZ1aBHbv7SYLEIkusNmUNJPo7K6DC8evTIOFdlU4w' 'sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM' 'sha384-Rw3AP/PSCWhQsOA9lwKQ02luSPa9fZgWLtCOKxopHsFosFOrQB5B00t2FoQ4HfJL' 'sha384-kZ2o2DO3rYuS/QkJv66LS3soqapWfnBpcQqnujbLHP8B0JIye0NiaI0SIuwOGJPW'; worker-src 'none';", 'x-content-type-options': 'nosniff', 'permissions-policy': 'fullscreen=(), geolocation=()', 'referrer-policy': 'no-referrer-when-downgrade', 'x-kanidm-version': '1.1.0-rc.15', 'strict-transport-security': 'max-age=86400', 'x-kanidm-opid': 'de51bf9f-1724-4c80-9496-aa621558ee5e', 'Date': 'Wed, 15 Nov 2023 23:22:26 GMT'}, status_code=500)
```

From preliminary testing in a REPL, it seems there are quite a few broken methods.

**Comment by sbordeyne** [comment]
I can run more manual tests as needed. Let me know how I can run the latest dev version of kanidm from your branch to make sure it's synced up (I see the PR includes some backend changes as well, can you push a tag to either the kanidm/server docker repo, or to your own repository on docker hub?) I'm unable to compile the image myself at the moment

**Comment by yaleman** [comment]
To start with, sorry for making this harder than it needed to be, I'm just very time-limited for testing such big changes at the moment 😞 

> I had a try, I ran kanidm in plain docker to test out the client (followed the evaluation quickstart guide, `kanidm/server:latest` image), and I had some issues:
> 
> ## Authentication
> The authentication is a bit weird to handle, though I managed
> 
> ```python
> client = KanidmClient(config=config)
> auth = await client.authenticate_password()
> client.config.auth_token = auth.state.success
> ```

If you set `update_internal_auth_token=True`, it means you don't have to keep authenticating.

> 
> allowed me to make authenticated calls using the `admin` user (`idm_admin` should therefore work as well)
> 
> The current process forces the operator to authenticate at each operation, which is not ideal, but for a first version it's good enough.
> 

^ You shouldn't have to keep authenticating. There's the beginnings of an integration test in `scripts/pykanidm/integration_test.py` that shows how things work. 

If you open two terminals and run:

1. `make run` in one (to build/run the server, you'll need a rust toolchain) and 
2. `python scripts/pykanidm/integration_test.py` in the other 

That'll run the integration script.

> ## Create user
> `await client.person_account_create("test", "test")` breaks, because `display_name` is not an allowed attribute
> 
> ```

Sorry, typo'd that.

> 
> ## Group create
> API error ? The group create endpoint doesn't return anything ?
> 

That should be fine as it didn't throw an **error** - there was an issue with deserialization of the response that was causing the `status_code=-1` and I've sorted that now.

> ```
> ClientResponse(content='', data=None, headers={}, status_code=-1)
> ```
> 


> ## password append
> badlist_passwordpayload is not correct ?
> 

Another dumb typo, sorry.


> From preliminary testing in a REPL, it seems there are quite a few broken methods.

Again, sorry, trying to manage my time/headspace at the moment considering this went from "add a few things" to "add a *lot* of things" 😄 I've updated the integration test I mentioned above to help test/sort these.

**Comment by sbordeyne** [comment]
Just FYI, I ended up with this solution to handle auth/logging https://github.com/sbordeyne/kanidm-operator/blob/master/kanidm_operator/auth.py 

Maybe adding in a logger kwarg to the client in itself would be a good idea too

**Comment by sbordeyne** [comment]
@yaleman I forked your repo, and am making the pydantic models (as well as some minor refactoring, to better fit the existing client architecture). I noticed though that calling the get endpoint for oauth2 doesn't return the client secrets, instead it shows "hidden" in the `attrs`, is it on purpose ? Is there documentation anywhere about the API endpoints ?

**Comment by yaleman** [comment]
> @yaleman I forked your repo, and am making the pydantic models (as well as some minor refactoring, to better fit the existing client architecture). I noticed though that calling the get endpoint for oauth2 doesn't return the client secrets, instead it shows "hidden" in the `attrs`, is it on purpose ? 

Yes, that's what happens in the CLI too, it's [called out in the OAuth2 docs](https://kanidm.github.io/kanidm/master/integrations/oauth2.html) (search for show-basic-secret) - there's a specific endpoint - it's `/v1/oauth2/{rs_name}/_basic_secret`. I've added the endpoint support in pykanidm

> Is there documentation anywhere about the API endpoints ?

Yes, the beginnings of an [OpenAPI spec is available when running your server](https://kanidm.github.io/kanidm/master/developers/designs/rest_interface.html)  -  it's still in its infancy at this time.

**Comment by Firstyear** [comment]
@yaleman This ready for review?

**Comment by yaleman** [comment]
Nope, will push it back to a draft, @sbordeyne is still PR'ing my PR 😄

**Comment by yaleman** [comment]
@Firstyear ready to go on this one

**Review by Firstyear — APPROVED** [review]

**Pull request merged**
