### PR TITLE
Ordering auth methods in the CLI

### PR DESCRIPTION
**Pull request by yaleman**
This orders the auth methods from "most secure" to "least secure" based on feedback from the community in Matrix.

Checklist

- [x] This pr contains no AI generated code
- [x] cargo fmt has been run
- [x] cargo clippy has been run
- [x] cargo test has been run and passes

### CODE REVIEW

**Comment by Firstyear** [comment]
Looks reasonable to me :)

**Comment by yaleman** [comment]
Waiting on someone to test it since I don't have multiple methods set up on any users and ... eh 😄

**Comment by Firstyear** [comment]
I have an account with that setup, I'll test it now.

**Comment by Firstyear** [comment]
good thing I tested!

**Review by Firstyear — APPROVED** [review]

**Pull request merged**
