### PR TITLE
20230629 tpm keygen   again

### PR DESCRIPTION
**Pull request by Firstyear**
- [ x ] This pr contains no AI generated code
- [ x ] cargo fmt has been run
- [ ] cargo clippy has been run
- [ x ] cargo test has been run and passes
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

### CODE REVIEW

**Review by yaleman — APPROVED** [review]
Ima trust you tested this in a few ways - I don't have a hardware/software solution for it yet 😄 

Since this has a feature flag, the automated testing won't catch anything - probably need to build this in at some point.

**Comment by Firstyear** [comment]
I'm not sure github has tpms on theis CI/CD :) 

And yes I have tested it :)

**Comment by yaleman** [comment]
(ref #1794)

**Comment by yaleman** [comment]
> I'm not sure github has tpms on theis CI/CD :)

yeah, it'd take shenanigans with software emulation I guess, just a thing to keep in the "one day" backlog.

**Pull request merged**
