### PR TITLE
ci: push docker image for git tags

### LINKED ISSUE #2855: No docker image was published to the docker hub for tag `1.2.3`
### I did this

`docker pull docker.io/kanidm/server:1.2.3`

### I expected the following

The docker image for the tagged 1.2.3 release should have been pulled

### This happened instead

the docker image does not exist

### Kanidm version details

- Output of `kanidm(d) version`:
- Are you running it in a container? If so, which image/tag?:
- If not a container, how'd you install it:
- Operating System / Version (On Unix please post the output of `uname -a`):

### Any other comments

Hello :wave: it looks like no docker image was pushed to ghcr or docker hub for the backported PR https://github.com/kanidm/kanidm/pull/2809 for the `1.2.3` tagged release (the [job appears to  have been skipped](https://github.com/kanidm/kanidm/actions/runs/9360056004/job/25765312832)). It seems this is because docker images are only pushed for the master branch:

https://github.com/kanidm/kanidm/blob/94e246e1cb3a486b19f2778aece1fc213d9726ee/.github/workflows/docker_build_kanidm.yml#L58

### PR DESCRIPTION
**Pull request by guillaumedsde**
Fixes #2855

This PR modifies the github action condition for the various docker image push jobs in order to push built images for the master branch *and* for git tags.

No source code was modified in this PR, only github workflow configuration.

Ideally tags could be prefixed with `v` in order to specifically target git tags meant for releasing a new kanidm version (as opposed to git tags used for experimenting) but in the meantime docker images will be pushed for all git tags.

I did not go the extra mile, but the github job for pushing docker imags could probably be extracted and reused to avoid code duplication and to avoid modifying code three times (once per docker image) when modifications are needed

Note that merging this PR will not build and publish a docker image for the `1.2.3` release, so building and pushing one manually to the docker hub registry will ensure that anyone looking for a tagged docker image for this release will find one.

Checklist

- [x] This pr contains no AI generated code
- [ ] cargo fmt has been run
- [ ] cargo clippy has been run
- [ ] cargo test has been run and passes
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

### CODE REVIEW

**Comment by yaleman** [comment]
This is a start but at the moment there's a difference between the automated GHA builds and what gets pushed to docker hub, because we've been unable to reliably build ARM images - the workflows you edited currently only push to the GitHub container registry...

**Comment by guillaumedsde** [comment]
ah, [i see](https://github.com/docker/build-push-action/issues/621). Until ARM64 builds are fixed, would this temporary solution of automatically publishing amd64 images to the github registry be acceptable or you'd rather have a coherent docker image offering (only `master` branch builds on the github registry and offer tagged releases on the dockerhub only)?

In any case, would it be possible to push the `1.2.3` image to the dockerhub? Currently it is only available (temporarily until it expires) in the CI build artifacts for the `1.2.0` branch, but downloading that ZIP, extracting it and importing it in the docker daemon is a bit painful.

**Comment by yaleman** [comment]
> ah, [i see](https://github.com/kanidm/kanidm/issues/818). Until ARM64 builds are fixed, would this temporary solution of automatically publishing tagged amd64 images to the github registry be acceptable or you'd rather have a coherent docker image offering (only `master` branch builds on the github registry and offer tagged releases on the dockerhub only)?

I like the idea, we really need to get the tagging right though in that case - currently it tags as "devel" only.

> In any case, would it be possible to push the `1.2.3` image to the dockerhub? Currently it is only available (temporarily until it expires) in the CI build artifacts for the `1.2.0` branch, but downloading that ZIP, extracting it and importing it in the docker daemon is a bit painful.

Yeah, I'll get that done today.

**Comment by Firstyear** [comment]
poking @yaleman to come back to this :)

**Pull request closed without merging**
