### PR TITLE
Project: Rewrite Python RLM into Rust (DRAFT)

### PR DESCRIPTION
**Pull request by czzrr**
Reference issue: #305

This is my first draft for the project of rewriting the Python RLM into Rust.
Please let me know if my understanding of the problem is off or if the scope is inappropriate. :-)

### CODE REVIEW

**Comment by yaleman** [comment]
FreeRADIUS calls the Python module using their [rlm_python3](https://freeradius.org/modules/?mod=rlm_python3) plugin which supports Python 3 modules natively. 

If you're going to change this, the path I'd see would be a C-based module that makes FFI calls into Rust... which is pretty cursed, but if you're up for it, then 🥳

**Comment by Firstyear** [comment]
I think the best place to start is to setup kani with freeradius and test it first.

Freeradius is written in C and can "dlopen" dynamic libraries (.so files). Because of how this works, the freeradius binary can call a specific "symbol" (aka function) that is exported as an entry point in that .so to start to use it.

A lot of this is documented here pretty coarsely https://wiki.freeradius.org/contributing/Modules3 

The idea of this would be that with Rust you can create a cdylib (which on linux becomes a .so) that has export/no_mangle symbols that match what freeradius expects when it dlopens the .so. Then the cdylib does all the same work that currently rlm_python does since rlm_python is itself a .so that is dlopened, and spawns a python interpretter to run the python code and pass thorugh the operations.

So this would mean looking at things like https://rust-lang.github.io/rust-bindgen/ which can assist here to automatically generate some of these entries, and then testing the module loading etc. 

Does that help explain? 

But regardless, setting up freeradius and testing it a bit will be absolutely necessary since the current "nice automatic" container method won't work while you're developing!

**Comment by czzrr** [comment]
> The idea of this would be that with Rust you can create a cdylib (which on linux becomes a .so) that has export/no_mangle symbols that match what freeradius expects when it dlopens the .so. Then the cdylib does all the same work that currently rlm_python does since rlm_python is itself a .so that is dlopened, and spawns a python interpretter to run the python code and pass thorugh the operations.

Just to be sure:
[rlm_python](https://github.com/FreeRADIUS/freeradius-server/tree/master/src/modules/rlm_python) is the C code that allows FreeRADIUS to call Python code natively.
Is the idea to rewrite the whole thing in Rust, or keep the base in C (like rlm_python) with calls to "custom scripts" written in Rust?

**Comment by Firstyear** [comment]
> > The idea of this would be that with Rust you can create a cdylib (which on linux becomes a .so) that has export/no_mangle symbols that match what freeradius expects when it dlopens the .so. Then the cdylib does all the same work that currently rlm_python does since rlm_python is itself a .so that is dlopened, and spawns a python interpretter to run the python code and pass thorugh the operations.
> 
> Just to be sure: [rlm_python](https://github.com/FreeRADIUS/freeradius-server/tree/master/src/modules/rlm_python) is the C code that allows FreeRADIUS to call Python code natively. Is the idea to

Correct,

> 
> 1. rewrite the whole thing in Rust with support for Rust custom scripts, interfacing with the FreeRADIUS C source code related to modules through FFI, or

Option 1. The whole thing will be Rust exposing FFI. Don't think about it as "scripts". It's a dedicated and focused module specific to our needs. 

> 2. keep the base in C (like rlm_python), following https://wiki.freeradius.org/contributing/Modules3, with FFI calls to Rust custom scripts?
> 
> **EDIT:** Rereading your comment and https://wiki.freeradius.org/contributing/Modules3, it sounds like 1. So things like the [module_t struct](https://wiki.freeradius.org/contributing/Modules3#module-development_module_t-struct) would be written in Rust in a C-compatible way with the help of rust-bindgen such that FreeRADIUS can properly load the module.

Yep!

**Comment by Firstyear** [comment]
Sounds good. You should be able to take apart the dockerfile for rlm python to set it up initially then you can go from there. FreeRADIUS is *notoriously* difficult and annoying to setup, so please ask for help if needed! In fact FreeRADIUS may even be the *most difficult* piece of opensource software to configure that I've ever seen outside of sendmail.

**Comment by czzrr** [comment]
I'm wondering how to set up a development environment for the Rust module.
Based on https://wiki.freeradius.org/contributing/Modules3, it sounds like we want to build the module and FreeRADIUS together. I can set up a development environment directly on my own machine, of course, but would it make sense to make a Docker image for this purpose, since we want to end up with one as the product anyway?
I suppose the current `rlm_python` Dockerfile can be used, but I would still need to rebuild FreeRADIUS with the module inside the container.

**Comment by Firstyear** [comment]
While you're developing this, you'll likely want to use a VM or similar to actually do your builds and tests allowing you to more quickly rebuild and test against the freeradius install on the VM. Once you make progress here and start to finalise, then you'll be more able to work that into a dockerfile to build the module in the correct way.

**Comment by czzrr** [comment]
Makes sense. Got ahead of myself there a bit.

Anyway, I played around with authenticating Kanidm users to the RADIUS server in the provided Docker image.
I'll try build RADIUS myself and get it working.

**Comment by Firstyear** [comment]
You don't need to build radius from sources, you only need to install the "same" as the docker image as well as freeradius-devel (at a guess) that will let you build/bindgen a module to use on the vm. Does that help?

**Comment by czzrr** [comment]
I think I misunderstood how FreeRADIUS knows about modules.
Is it the case that it loads (dynamically links) *all* modules (.so files) upon startup? If so, what you said makes sense. (FreeRADIUS does not need to be built with modules to know about them.)
The Rust module's .so file could then be placed among the others to be used.

**Comment by Firstyear** [comment]
FreeRADIUS doesn't *link* to the modules. It dlopens them. All FreeRADIUS cares about is that your module has a certain set of known symbols exported that it can call after the dlopen completes. :)

**Comment by Firstyear** [comment]
> I think it would be nice for me to start off by making a minimalistic module that does nothing but print some dummy message or returns a fixed rlm code.

That is exactly the right way to start :) 

> I looked at the freeradius-dev headers, and there's a lot of macros and dependencies for the relevant definitions. Is it ok to just ad-hoc/manually add whatever I need to a common header file that I can run bindgen on?

For sure, that's okay. You could also bind gen and then cherry pick what you need from what it generated. 

> 
> @Firstyear I will also begin preparing my application, which I will share with you elsewhere. 😀

Feel free to email me :)

**Comment by Firstyear** [comment]
@czzrr Reminder to address this part in your gsoc submission too:

> Assessment: Our intent is to mentor and help you grow as a contributor - and we want to help you succeed! As this is our focus, we have different assessment criteria to many other projects.
> 
> Has the student:
> 
> participated actively in the project?
> written and submitted personal blog/journal or similar about the experience and what they have learnt and attempted?
> sufficiently attempted one or any of the offered deliverables? (Note - there is no requirement to complete the deliverable. Just evidence of a solid attempt)

**Pull request closed without merging**
