### PR TITLE
re-adding ARM builds and adding build tweaks

### LINKED ISSUE #818: Automated ARM build failures
The docker_build GitHub Action keeps failing on ARM builds because of OOMkiller (`exit code 137`)

Looks to relate to this: https://github.com/docker/build-push-action/issues/621 where dockerized ARM builds in github actions + rust = fail 😢

### PR DESCRIPTION
**Pull request by yaleman**
Fixes #818

### CODE REVIEW

**Comment by Firstyear** [comment]
https://github.com/openSUSE/zypper/issues/478

**Comment by Firstyear** [comment]
Still looks cooked :(  Sigh

**Comment by yaleman** [comment]
I give up on this for now, the openSUSE images are just too broken.

**Comment by Firstyear** [comment]
😢

**Comment by Firstyear** [comment]
https://bugzilla.opensuse.org/show_bug.cgi?id=1209031

**Pull request closed without merging**
