### PR TITLE
Proposal for name change history

### LINKED ISSUE #345: hidden name history
It may be useful to have a "name history" for previous legalname/displaynames/name fields so that username changes and associations can be looked up post-fact. this is a sensitive field so should be protected by default. 

Again, knowing the use cases here would be good. From a security view, to track the history of changes, it may be better to have an audit/event system (which is already a planned feature), where as from a support or service desk view it could be useful for undoing/rolling back changes (but this could also be done via the repl changelog.). 

If this implemented the feature should have a boolean config in the domain config, disabled by default. 

If enabled, another option is to prevent re-use of an already claimed name. IE if someone is named 'a' and renames to 'b', then no other account should be able to claim the name 'a' - it effectively becomes "archived". A question is how to handle this when the account is deleted. If the name should be "forever" archieved. 

Note that an abuse prevention is needed here so that if they name changes "too much" then it is disallowed or requires admin intervention.

### PR DESCRIPTION
**Pull request by MinhPhan8803**
References #345 

- [ ] cargo fmt has been run
- [ ] cargo clippy has been run
- [ ] cargo test has been run and passes
- [ ] book chapter included (if relevant)
- [x] design document included (if relevant)

Pretty short proposal for now.

### CODE REVIEW

**Comment by yaleman** [comment]
Updated your comment so it shouldn't auto-close the issue, if this is just a proposal.

**Comment by MinhPhan8803** [comment]
> Updated your comment so it shouldn't auto-close the issue, if this is just a proposal.

Thank you! I also changed the PR name to be more descriptive. The previous one was written midnight and was eh not the best.

**Comment by Firstyear** [comment]
You could probably expand this a bit, wrt to testing and include the link to the issue. Also note that if you finish "early" there are plenty of other things we can work on with you too, so possibly include that in there as well. :)

**Comment by MinhPhan8803** [comment]
I just added a few stuff to the proposal :)

**Comment by MinhPhan8803** [comment]
Should I put project size as medium or large?

**Comment by Firstyear** [comment]
medium I think :)

**Comment by MinhPhan8803** [comment]
Also is there anything I should elaborate on wrt to testing and related stuff?

**Comment by Firstyear** [comment]
That's all expected anyway, test design and inclusion was always part of any featuire IMO so doesn't need special call outs. Just re-review the original task per https://github.com/openSUSE/mentoring/issues/196 and make sure you can do the "assessment tasks"

**Comment by MinhPhan8803** [comment]
Thank you!

**Comment by MinhPhan8803** [comment]
Wait the assessment looks like it would be for *during* the project right?

**Comment by Firstyear** [comment]
What do you mean by "during"?

**Comment by MinhPhan8803** [comment]
I mean like for if we are selected (for GSOC), the assessment will be used for the mentor evaluation part.

**Comment by Firstyear** [comment]
Yeah, I'm saying that in your application you need to understand that during the project you'll need to write about your experiences and contribute generally, so bring up that in your application  and how you want to approach it.

**Comment by MinhPhan8803** [comment]
I see thank you :)

**Comment by MinhPhan8803** [comment]
@Firstyear I just sent an email to your SUSE address. Can you take a look at that?

**Pull request closed without merging**
