### PR TITLE
Add note on snaps to PAM and nsswitch with link to new section in FAQ

### LINKED ISSUE #2233: Suggestion: Update unixd home_alias note for Ubuntu users
Hello, I ran into an issue with snaps on Ubuntu using this configuration for unixd:  

```
home_attr = "uuid"
home_alias = "name"
```  
It turns out that there's a known issue with snaps and symlinked home directories due to an apparmor constraint: 

[Unable to run snap, because of home directory](https://forum.snapcraft.io/t/unable-to-run-snap-because-of-home-directory/25138)  

[when /home is somewhere else, snaps don't work ](https://bugs.launchpad.net/snapd/+bug/1620771)  

I was testing posix logins in a Kubuntu virtual machine and noticed this was the case when firefox wouldn't launch which is a snap by default in most Ubuntu distributions.   

Not a big deal for myself personally as I don't mind doing manual renames if I were to ever change the account name and my setup for Ubuntu is now:  
```
home_attr = "name"
home_alias = "none"
```  
It might be worthwhile to update either the notice on pam_and_nsswitch.md, or add it to frequently_asked_questions.md, with a mention of this for Ubuntu users as Canonical is gung-ho about defaulting as much as possible to snaps going forward.

### PR DESCRIPTION
**Pull request by kenjitamura**
Fixes #2233

I think this addresses what was discussed in #2233 but probably could use corrections for comprehension if you spot anything.

Checklist

- [X ] This pr contains no AI generated code

### CODE REVIEW

**Review by Firstyear — APPROVED** [review]
I think this works well for our docs :)

**Comment by Firstyear** [comment]
Thank you @kenjitamura !

**Comment by kenjitamura** [comment]
I'll be happy if someone finds it useful.  I'm still just getting started with kanidm in my home lab but I was impressed with how simple it was to get up and running so thank you for this project!

**Comment by Firstyear** [comment]
If you have more questions or feedback, please let us know :)

**Pull request merged**
