### PR TITLE
Initial thoughts about oauth2 app listing

### PR DESCRIPTION
**Pull request by Firstyear**
Fixes #

- [ ] cargo fmt has been run
- [ ] cargo clippy has been run
- [ ] cargo test has been run and passes
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

### CODE REVIEW

**Comment by yaleman** [comment]
Looks sensible so far, thanks for putting it into words 😄 

## Implicit scope removal

For the migration to the new config and removal of implicit scopes, would it be relatively trivial to:

- create an `all_people` (or similar) group
- automagically add all existing `Person` accounts to it 
- add it as the access scope for any existing OAuth2 RS

For a one-off change during Alpha-mode it might be a load of work (and thus ... meh?) But would save a little surprise.

## Images

That's going to be fun 😄 I'd definitely go with PNG/SVGs from a size perspective and limit the size to... rather small either way. User images can be done in a similar way 🥳

**Comment by Firstyear** [comment]
I've already done the all people migrate so that's done :) 

Now just to add the access controls, but for now I think all users can read the outh2 public config parts?

**Comment by yaleman** [comment]
It does look that way - were we going to make the origin public?

**Comment by Firstyear** [comment]
I think it has to be so we can present the link to the users to actually render and follow from the front page.

**Comment by Firstyear** [comment]
I'll submit some acp changes for this today.

**Pull request merged**
