### PR TITLE
Add github actions:

### PR DESCRIPTION
**Pull request by pando85**
- Add linter with `cargo fmt`
- Add tests
- Add server docker build
- Add radius docker build
- Fix kanidm_unix_int format to pass tests

### CODE REVIEW

**Comment by pando85** [comment]
This PR is tested against my [fork master](https://github.com/pando85/kanidm).

This allows to lint and test every commit except that with only affects documentation files. Build all commits in master and create `kanidmd` and `kanidm_rlm_python` images latest for every commit and tagged against `v*` tags.

You will need to setup your `DOCKERHUB_TOKEN` and `DOCKERHUB_USERNAME` as secrets in Github settings.

This is a basic CI but improves current one and could be improve.

**Comment by pando85** [comment]
I tested here with other image names: [kanidmd](https://hub.docker.com/repository/docker/pando85/kanidmd) and [kanidm_rlm_python](https://hub.docker.com/r/pando85/kanidm_rlm_python).

**Comment by pando85** [comment]
This could close #97

**Comment by Firstyear** [comment]
Hey there, this looks really cool. I didn't have time to review it today, but I promise I'll look tomorrow. Thanks so much!

**Comment by Firstyear** [comment]
Hey there, I already have docker hub configured to automatically pull and build, so I think I'll stick to that for the moment. Is it okay to just have the fmt/build/test work action in this change? Thanks!

**Comment by pando85** [comment]
Hey! Ok if you want I could remove that jobs. I know that it's not the most elegant ones, it's almost copy paste but I think that improve docker hub ones.
- Docker hub radius is actually failing and this fix it.
- this approach gives repository control over docker build configurations, that could be a little advantage.
- I don't know if that jobs build on tags to release but this could be useful.
- although this builds launch tests over docker images in all PRs that could be an advantage.

If you want to explain more about that I could find another approach that convince you more.

This is a first step to have a proper CI to automatize realises, I used GitHub actions because I wanted to try them but if you have preference for other software/technology I could implement it.

**Comment by Firstyear** [comment]
Maybe I should do it this way. Docker hub is really slow to build and I didn't know it was failing to build :| so that's not good! 

But yeah, I like the idea of automating releases based on tags, so you know, I think I changed my mind and I'll accept this :) I need to do a few other things for work at the moment, but I'll merge this afternoon and setup the keys and tokens :) 

Thanks very much!

PS: I setup https://gitter.im/kanidm/community to chat if you want to talk about things a bit easier. My timezone is UTC +10:00

**Pull request merged**
