### PR TITLE
Resolve `tracing` bugs + minor refactoring

### PR DESCRIPTION
**Pull request by QnnOkabayashi**
Fixes #

- [x] cargo fmt has been run
- [x] cargo clippy has been run
- [x] cargo test has been run and passes
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

Resolves some minor bugs with `tracing`, and also utilizes `all` and `any` to make `server.rs` more idiomatic.

### CODE REVIEW

**Comment by QnnOkabayashi** [comment]
I have no idea why so many commits are showing up but only the last 4 are what I did.

**Comment by Firstyear** [comment]
@QnnOkabayashi You may not have checked out master before you started working. You can fix this with:

```
git rebase -i HEAD~4
```

Then squash your work to a single commit. Use git log to take a note of the single commit hash. 

Then do:

```
git checkout master
git branch -M idiomatic-refactoring idiomatic-refactoring-broken
git checkout -b idiomatic-refactoring
git cherry-pick <commit hash>
```

Then rebuild and retest :) Once done you'll need to `git push <your fork> idiomatic-refactoring --force` to overright the commits in this branch.

Hope that helps!

**Comment by QnnOkabayashi** [comment]
I tried this and everything went south and I had to delete my repo and reclone. Is there anything wrong with the current commit? All the tests pass and there aren't any conflicts.

**Comment by Firstyear** [comment]
Closing in favour of rebased PR #570

**Pull request closed without merging**
