### PR TITLE
Correcting command typo, works with kanidm/server img ac1fddd16083

### PR DESCRIPTION
**Pull request by jonathanknez**
Fixes # - NA, I am lazy and this is just a doc change.

- [ ] cargo fmt has been run
- [ ] cargo clippy has been run
- [ ] cargo test has been run and passes
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

### CODE REVIEW

**Comment by yaleman** [comment]
So... this is awkward. The *current* command is `recover-account`, which changed a while ago...


https://github.com/kanidm/kanidm/blob/d26bef17b679a8a4944d87fef52cdaf3ef46042c/server/daemon/src/opt.rs#L139

**Comment by jonathanknez** [comment]
Thanks for checking. I pulled index.docker.io/kanidm/server:latest on my raspberry pi and got an image from 2022-11-09. Checking your release history, that probably makes it one release old, v1.1.0-alpha.10. Do you know if there is an alpha11 pre-built image available?

**Comment by Firstyear** [comment]
I'm wondering if we botched something with the arches on the aarch images? There has been some weirdness with docker/buildx recently wher they are setting arches from things like "linux/amd64" to "linux/amd64/v2" for example. 

Looking at https://hub.docker.com/repository/docker/kanidm/server/tags?page=1&ordering=last_updated it's showing these as last pushed 4 months ago which means we may have missed a step in release? 

I'll try to fix these images up today @jonathanknez

**Comment by Firstyear** [comment]
Ahh that's right, it's related to https://github.com/docker/buildx/issues/1686

**Comment by Firstyear** [comment]
Okay, I have fixed the published images for latest @jonathanknez really sorry about that.

**Pull request closed without merging**
