### PR TITLE
Rough working login page

### PR DESCRIPTION
**Pull request by Firstyear**
This is an *extremely* rough finish to the login screen. There are still many un-handled cases and credential types, but it works at a basic level. 

- [ x ] cargo fmt has been run
- [ - ] cargo clippy has been run
- [ x ] cargo test has been run and passes
- [ - ] book chapter included (if relevant)
- [ - ] design document included (if relevant)

### CODE REVIEW

**Comment by vDorst** [comment]
I got: `Handler::Webauthn -> Result::Denied - webauthn error InvalidRPOrigin` when trying to login with WebAuthn.

I shall email you the logs.

**Comment by Firstyear** [comment]
@vDorst Hey there,

You may need to update your origin in server.toml. As I learnt yesterday, the port number is required if it's not 443. That's the most likely cause of this issue.

**Comment by vDorst** [comment]
@Firstyear Yes that is the issue. My origin url didn't had a port number.

Real funny all the confetti, I like that :)

**Comment by Firstyear** [comment]
> @Firstyear Yes that is the issue. My origin url didn't had a port number.
> 

The docs in the book have been updated to include this :)

**Pull request merged**
