### PR TITLE
Document the Makefile and its variables

### LINKED ISSUE #768: docs - explain the Makefile options for developers
**Documentation for Makefile usage**

As a developer, it would be handy to have documentation of options for the `Makefile` and a general theory of what's expected.

For example, I'm curious what [the `ARGS` reference is to a `redis` cache](https://github.com/kanidm/kanidm/blob/ec7c3cc6238459e7098c0ae948f4fb21fb27439e/Makefile#L7).

**Describe the solution you'd like**

Identify whether it is preferable to update `DEVELOPER_README.md` or create a new document with a clear name such as `BUILDING_CONTAINERS.md` and document the various options available to build a `kanidmd` container image.

**Describe alternatives you've considered**

There's the Star Wars method - `use the source, Luke` - which is what I used my first time through the process.

### PR DESCRIPTION
**Pull request by kellinm**
```
Document the Makefile and its variables

- Adds documentation of the Makefile and its variables with an example
  of how to change build behavior.

Closes https://github.com/kanidm/kanidm/issues/768

Signed-off-by: Kellin <kellin@retromud.org>
```

Fixes #768 

- [ ] cargo fmt has been run
- [ ] cargo clippy has been run
- [ ] cargo test has been run and passes
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

### CODE REVIEW

**Comment by yaleman** [comment]
While we're working on this, I'd really like to see the argument naming changed. Having `EXT_ARGS` and `ARGS` is a little... confusing, when `EXT_ARGS` is handed to the container build tool, and `ARGS` is being handed to rust inside the container.

Can I suggeest the following changes in the Makefile?

- rename `ARGS` to `BUILD_ARGS`
- rename `EXT_ARGS` to `CONTAINER_ARGS` (or maybe `CONTAINER_TOOL_ARGS`).

This'd match the `CONTAINER_TOOL` arg added in a recent change. Ping @Firstyear since he uses this for things.

**Comment by Firstyear** [comment]
Im certainly cool with the rename to CONTAINER_ARGS, I think it's a good idea.

I think the Makefile was more intended for "kind of" releases rather than development, but I guess we can take it that way and tidy it up as both a release and dev tool. 

And at some point I have to stop hardcoding in things that just benefit my build infra, and externalise some of that 🤣

So how about we rename those arges, and default the sccache_redis to blank, but give an example of when it could be used?

**Review by Firstyear — APPROVED** [review]

**Comment by Firstyear** [comment]
@yaleman Want to press the buttons?

**Comment by yaleman** [comment]
Boop!

**Comment by kellinm** [comment]
Oh, I was still refinding the merge request heh.

**Comment by Firstyear** [comment]
Sorry, we're just too eager to merge clearly :) 

Just submit another PR/branch and mark it draft until it's ready?

**Comment by kellinm** [comment]
Opened one, it's ready for you - I had just come back into the UI to post an update and noticed that it was already merged. That's my fault for forgetting to set Draft mode.

**Pull request merged**
