### PR TITLE
Add env var KANIDM_TOKEN_PATH

### PR DESCRIPTION
**Pull request by tumbl3w33d**
that allows overriding the path where the CLI client searches for its token store.

That's especially useful when you run multiple environments and want to switch on a per-directory base, e.g., using tools like direnv.

Fixes #

Checklist

- [ x] This pr contains no AI generated code
- [x ] cargo fmt has been run
- [x ] cargo clippy has been run
- [ x] cargo test has been run and passes
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

### CODE REVIEW

**Comment by yaleman** [comment]
I'd definitely rather this be a hidden option in the `clap` parser than something buried in that part of the code.

**Comment by tumbl3w33d** [comment]
Then you would need to pass it explicitly on every execution, which is quite inconvenient. I'd see this being used with something like direenv to automatically pick up the env per execution environment.  It could be done in clap in addition, though. What is your motivation of hiding it?

I'm fine with picking up the vars in a different place than this here if you want to suggest one.

**Comment by yaleman** [comment]
> Then you would need to pass it explicitly on every execution, which is quite inconvenient. 

Not at all, see similar example here for passing passwords in with an env var: https://github.com/kanidm/kanidm/blob/41aa315f23a4ae7705b06ed71013bc5014f0c8ee/tools/cli/src/opt/kanidm.rs#L535

**Comment by Firstyear** [comment]
I think my question here is "what are you trying to achieve" @tumbl3w33d. I think this relates to your desire to do ansible-ish state based operations on the server. Are you trying to use the cli tool for scripting?

**Comment by Firstyear** [comment]
Also as a gentle reminder to everyone, per https://github.com/kanidm/kanidm/blob/master/project_docs/RELEASE_AND_SUPPORT.md#api-stability "The CLI is not an API and can change with the interest of human interaction during any release." 

So I think we need to seriously consider a seperate tool for scripting rather than overloading the current cli tool, and likely we need to do that with scim in place since that's the best / closest representation to what people here want to achieve.

**Comment by Firstyear** [comment]
@tumbl3w33d Also note, since you are syncing users from an external source you *should* consider a sync driver instead https://kanidm.github.io/kanidm/stable/sync/concepts.html so that the entries have attribute protection and reflection that they are externally controlled.

**Comment by tumbl3w33d** [comment]
Nope, not this time. :)

I already have 3 environments (production, a test environment and now a dev setup) and I want to switch context with the CLI when working with them.

**Comment by Firstyear** [comment]
> Nope, not this time. :)
> 
> I already have 3 environments (production, a test environment and now a dev setup) and I want to switch context with the CLI when working with them.

In git master there is an update so that the tokens are bound to the spn not name so you can have multiple environments here. 

Second, @yaleman has an "environment config" switcher, though I think we should consider having it in mainline so that people can have a config like:

```
[default]
uri = ...

[dev]
uri = ...

[stage]
uri = ...
```

Then you can select the env with kanidm -e dev <commands>.

I think that's a far better solution to your problem than allowing tokens in env.

**Comment by tumbl3w33d** [comment]
Yeah, your proposal in combination with the clap-induced env var to select it would be great. So I am closing this.

I will go down the python module route for now and thanks for your hint to the sync functionality advantage. Didn't think that's relevant for my use case, but I understood now.

**Comment by yaleman** [comment]
I use https://github.com/yaleman/kanidm-profiles as my profile-switcher, for reference.

**Comment by Firstyear** [comment]
I think we should have a profile switcher internally in the kanidm tool, should we leave this open to achieve that? Can we open an issue for it?

**Pull request closed without merging**
