### PR TITLE
Add Ubuntu in the installation guide

### PR DESCRIPTION
**Pull request by Daniel-Boluda**
Add Ubuntu in the installation guide

### CODE REVIEW

**Review by yaleman — CHANGES_REQUESTED** [review]
Given the current "kinda-hacked-together" format of the PPA, please change the instructions to just linking to https://kanidm.github.io/kanidm_ppa/ instead, so we don't have to keep them synchronised.

**Comment by aduzsardi** [comment]
Howdy,
Am i right to assume that only ubuntu 22.04+ is supported ?

**Comment by yaleman** [comment]
Any (reasonable) version you can build the tools on is supported, the PPAs are automatically built from the `master` branch based on scripts that have been submitted by the community, and it's best-effort from there.

**Comment by yaleman** [comment]
Duplicate of #2928

**Pull request closed without merging**
